### ISSUE TITLE
Other OS support

### ISSUE THREAD

**Issue by aleksul** [AustinScola/pytest-motor#29]
Hello @AustinScola!

I know that your project currently supports only Ubuntu (as issue #13 says) so this issue should be marked as enhancement. However, if you're planning on adding Windows support (which I'm personally really looking forward), here is my small research.

Seems like PR #21 adds an ability to run your add-on on macOS. I tweaked frepond's fork to support Windows. Predictably, it doesn't work because of Unix sockets. So one way is to implement sockets part differently.

Another suggestion I have is to add an ability to run over an existing MongoDB installation or MongoDB docker container. It might be configured with setup.cfg near to pytest itself.

Anyway, I'm leaving this decision up to you. Let me know if I can help with code.

**Comment by AustinScola** [comment]
Hey @aleksul, you are correct that `pytest-motor` only supports Ubuntu at the moment and that MacOS support is in the process of being added. I didn't have any plans to add Windows support in the near future, but I would be more than happy to work with you or others on adding it if you desire. (I don't have a Windows machine to test on though.)

My first thought for support would be to use a random port instead. I know that `aiohttp` has a method [`pytest_aiohttp.aiohttp_unused_port`](https://docs.aiohttp.org/en/latest/testing.html#pytest_aiohttp.aiohttp_unused_port) for finding a random port. We could look at how that is implemented for reference.

I like the sound of using an existing installation or MongoDB docker container as well too. Those both sound like longer term efforts though.

**Comment by aleksul** [comment]
Ok, so it sounds like firstly we need to resolve #17. I will create PR asap.
