### ISSUE TITLE
`mypy` exclude improperly configured

### ISSUE THREAD

**Issue by aleksul** [AustinScola/pytest-motor#38]
> This isn't dedicated to this PR, but I would suggest a small change in mypy script
> from
> `python3 -m mypy .`
> to
> `python3 -m mypy ./pytest_motor ./test_data ./tests`
> because otherwise mypy scans venvs directory.

The `mypy.ini` has an `exclude` line to prevent that:
```ini
exclude=/venvs/
```

And generally, I prefer excluding files to check rather than including because it is very easy to add new files and not realize that `mypy` isn't checking them if you list includes.

_Originally posted by @AustinScola in https://github.com/AustinScola/pytest-motor/issues/36#issuecomment-881872646_

**Comment by AustinScola** [comment]
Maybe you misinterpretted my comment? I meant that `mypy.ini` already has an exclude:

https://github.com/AustinScola/pytest-motor/blob/7da7da0e67b7c2c826f4cd2b49d32a975307b28b/mypy.ini#L5

**Comment by aleksul** [comment]
Here is the thing:
venvs isn't the top directory, so `exclude=/venvs/` doesn't exclude venvs folder, it should be `exclude=venvs/` instead.

Here is the image with and without the change on my PC:

![изображение](https://user-images.githubusercontent.com/63556725/126034192-db36dbbe-ac20-4292-80ae-fd89a382e8a1.png)

**Comment by AustinScola** [comment]
Ahh, you are right. We either want `./venvs/` or `venvs/`!

**Comment by aleksul** [comment]
> 
> 
> Ahh, you are right. We either want `./venvs/` or `venvs/`!

`./venvs/` also doesn't work for some reason (at least, on my machine) but `venvs/` does

![изображение](https://user-images.githubusercontent.com/63556725/126034297-fabd0e3d-d190-4604-a59e-d548627ca3ac.png)

![изображение](https://user-images.githubusercontent.com/63556725/126034310-fa658563-319a-48d7-a525-d5b22fb956df.png)

**Comment by AustinScola** [comment]
Might need some escaping? [Docs](https://mypy.readthedocs.io/en/stable/config_file.html#confval-exclude) say that it is a regex.

**Comment by aleksul** [comment]
> 
> 
> Might need some escaping? [Docs](https://mypy.readthedocs.io/en/stable/config_file.html#confval-exclude) say that it is a regex.

I'm not very good at regex and can't find any way to make `./venvs/` work. I think, though, `venvs/` might be the thing.

**Comment by AustinScola** [comment]
Sounds good to me. Thanks for finding this!
